# Generated by Django 3.2.13 on 2022-05-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='created',
            new_name='add_date',
        ),
    ]
