# Generated by Django 4.0.3 on 2022-04-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredients',
            options={'verbose_name': 'Количество ингредиента для конкретного рецепта', 'verbose_name_plural': 'Количество ингредиентов для конкретного рецепта'},
        ),
    ]
