# Generated by Django 4.0.3 on 2022-05-04 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_amountofingredients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredients',
            options={'ordering': ['-id'], 'verbose_name': 'Количество ингредиента для конкретного рецепта', 'verbose_name_plural': 'Количество ингредиентов для конкретного рецепта'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше еденицы')], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше одной минуты')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку', null=True, upload_to='static/recipe/', verbose_name='Картинка к рецепту'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Введите название рецепта', max_length=200, verbose_name='Название рецепта'),
        ),
        migrations.AddConstraint(
            model_name='amountofingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient'),
        ),
    ]
