# Generated by Django 4.0.3 on 2022-05-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountofingredients_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='measurement_unit',
        ),
    ]
