# Generated by Django 4.0.3 on 2022-05-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='ingredient',
            field=models.ForeignKey(help_text='Поле связанное с ингредиентом', on_delete=django.db.models.deletion.CASCADE, related_name='amountofingredient', to='recipes.ingredient', verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(help_text='Поле связанное с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='amountofingredient', to='recipes.recipe', verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Введите название ингредиентов и их количество', related_name='recipes', through='recipes.AmountOfIngredients', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
