# Generated by Django 4.0.3 on 2022-05-10 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_alter_amountofingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='ingredient',
            field=models.ForeignKey(help_text='Поле связанное с ингредиентом', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient', verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(help_text='Поле связанное с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.recipe', verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Введите название ингредиентов и их количество', through='recipes.AmountOfIngredients', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
