# Generated by Django 3.2.13 on 2022-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220514_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Введите цвет тега в формате HEX-кода', max_length=50, unique=True, verbose_name='Цвет тега в формате HEX-кода'),
        ),
    ]
