# Generated by Django 4.0.3 on 2022-05-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(help_text='Поле связанное с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.recipe', verbose_name='Название рецепта'),
        ),
    ]
