# Generated by Django 4.0.3 on 2022-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_author_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Введите название ингредиентов и их количество', related_name='recipes', through='recipes.AmountOfIngredients', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
