# Generated by Django 4.0.3 on 2022-05-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='ingredient',
            field=models.ForeignKey(help_text='Поле связанное с ингредиентом', on_delete=django.db.models.deletion.CASCADE, related_name='amount_ingredients', to='recipes.ingredient', verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(help_text='Поле связанное с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='amount_ingredients', to='recipes.recipe', verbose_name='Название рецепта'),
        ),
    ]
