# Generated by Django 4.0.3 on 2022-05-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_shoppingcart_recipe_shoppingcart_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping',
        ),
    ]
