# Generated by Django 4.0.3 on 2022-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': [
                '-id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='follow',
            name='add_date',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-02-02 22:22', verbose_name='Дата подписки'),
            preserve_default=False,
        ),
    ]
